# python
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7

export VIRTUALENVWRAPPER_PYTHON=`which python3`
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv

export WORKON_HOME=$HOME/venvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

if [ -f ~/.hub-completion.bash ]; then
  . ~/.hub-completion.bash
fi

# git
eval "$(hub alias -s)"
alias gap="git add -p"
alias gl="git log --oneline --pretty"
alias gf="git fetch origin"

# bash
alias ll="ls -la"

export EDITOR=/usr/bin/vim
source /Users/shaunokeefe/dev/stile/operations/bashrc

PATH=$PATH:/Users/shaunokeefe/dev/stile/operations/tools/cfnplus/
PATH=$PATH:/Users/shaunokeefe/dev/stile/operations/tools/bin/
