# python
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv

export WORKON_HOME=$HOME/venvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# git
eval "$(hub alias -s)"
alias gap="git add -p"
alias gl="git log --oneline --pretty"
alias gf="git fetch origin"

# bash
alias ll="ls -la"

export EDITOR=/usr/bin/vim
